apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: user-service-image:latest
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: user-service-config
        - secretRef:
            name: user-service-secret
        volumeMounts:
        - mountPath: "/data"
          name: user-service-pvc
      volumes:
      - name: user-service-pvc
        persistentVolumeClaim:
          claimName: user-service-pvc