name: Build and Test Event Service

on:
  push:
    paths:
      - 'event-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: cd event-service && npm install

    - name: Run Tests
      run: cd event-service && npm test

    - name: Build UBI-based Docker Image
      run: cd event-service && docker build -t quay.io/szigmon/event-service:$GITHUB_SHA .

    - name: Login to Quay.io
      run: docker login quay.io -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }}

    - name: Push UBI-based Docker Image to Quay.io
      run: docker push quay.io/szigmon/event-service:$GITHUB_SHA
